-- MySQL Script generated by MySQL Workbench
-- Sun Feb 28 09:34:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema` DEFAULT CHARACTER SET utf8 ;
USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`sala` (
  `nome_sala` VARCHAR(255) NOT NULL,
  `cod_sala` INT NOT NULL,
  `id_sala` INT NOT NULL AUTO_INCREMENT,
  `capa_sala` INT NOT NULL,
  `etapa_sala` INT NOT NULL,
  `event_id_event` INT NOT NULL,
  PRIMARY KEY (`id_sala`));


-- -----------------------------------------------------
-- Table `sistema`.`coffee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`coffee` (
  `id_coffee` INT NOT NULL AUTO_INCREMENT,
  `nome_coffee` VARCHAR(255) NOT NULL,
  `capa_coffee` INT NOT NULL,
  PRIMARY KEY (`id_coffee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`event` (
  `nome_event` VARCHAR(255) NOT NULL,
  `etapa_event` INT NOT NULL,
  `data_event` DATE NOT NULL,
  `id_event` INT NOT NULL AUTO_INCREMENT,
  `sala_id_sala` INT NOT NULL,
  `coffee_id_coffee` INT NOT NULL,
  PRIMARY KEY (`id_event`, `nome_event`, `etapa_event`),
  INDEX `fk_cad_sala1_idx` (`sala_id_sala` ASC) ,
  INDEX `fk_event_coffee1_idx` (`coffee_id_coffee` ASC) ,
  CONSTRAINT `fk_cad_sala1`
    FOREIGN KEY (`sala_id_sala`)
    REFERENCES `sistema`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_coffee1`
    FOREIGN KEY (`coffee_id_coffee`)
    REFERENCES `sistema`.`coffee` (`id_coffee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `sistema`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`participante` (
  `nome_part` VARCHAR(255) NOT NULL,
  `snome_part` VARCHAR(255) NOT NULL,
  `email_part` VARCHAR(255) NOT NULL,
  `nasci_part` DATE NOT NULL,
  `id_part` INT NOT NULL AUTO_INCREMENT,
  `event_id_event` INT NOT NULL,
  PRIMARY KEY (`id_part`, `nome_part`),
  INDEX `fk_participante_event1_idx` (`event_id_event` ASC) ,
  CONSTRAINT `fk_participante_event1`
    FOREIGN KEY (`event_id_event`)
    REFERENCES `sistema`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `sistema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`user` (
  `nome_cad` VARCHAR(255) NOT NULL,
  `snome_cad` VARCHAR(255) NOT NULL,
  `email_cad` VARCHAR(255) NOT NULL,
  `senha_cad` VARCHAR(32) NOT NULL,
  `emp_cad` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nasci_cad` DATE NOT NULL,
  PRIMARY KEY (`id_user`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
